---
- name: "Build container with ansible"
  hosts: localhost
  tasks:
    - name: stop running container
      command: docker stop iti-page
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm iti-page
      ignore_errors: yes

    - name: remove used image
      command: docker rmi 0xze/iti-page:latest
      ignore_errors: yes

    - name: build docker image from Dockerfile
      command: docker build -t 0xze/iti-page:latest ../App

    - name: push image to dockerhub
      command: docker push 0xze/iti-page:latest