apiVersion: apps/v1 
kind: Deployment
metadata:
  name: iti-page-deployment 
  namespace: app
spec:
  selector:
    matchLabels:
      app: ITI-page
  replicas: 2
  template:
    metadata:
      labels:
        app: ITI-page
    spec:
      containers:
      - name: iti-page
        image: 0xze/iti-page:latest
        ports:
        - containerPort: 80
