apiVersion: v1
kind: Service
metadata:
  name: iti-page-service
  namespace: app
spec:
  selector:
    app: ITI-page
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80 
