apiVersion: v1
kind: Service
metadata:
  name: ITI-page
  namespace: App
spec:
  selector:
    app: ITI-page
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80 